# Generated by Django 5.0.2 on 2024-02-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNo', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
                ('confPass', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='vendorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shopName', models.CharField(max_length=50)),
                ('shopAddress', models.CharField(max_length=50)),
                ('shopLicence', models.ImageField(blank=True, upload_to='Licence')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('vendorMail', models.EmailField(max_length=254)),
                ('vendorPhone', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('confPass', models.CharField(max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
